### ISSUE TITLE
Unresolved reference 'chord'

### ISSUE THREAD

**Issue by Sususuqii** [bunnerlemon/AutoMusic#1]
elif isinstance(element, chord.Chord):
                    # print("chord=", '.'.join(str(data) for data in element.normalOrder))
                    last_chord_idx = chord2int['.'.join(str(data) for data in element.normalOrder)]
                    flag = False

位置：data_pure.py   103行处
问题  ：chord处标红，显示：Unresolved reference 'chord' 
我尝试着安装了chord，但是并没有作用

谢谢您

**Comment by bunnerlemon** [comment]
我使用的chord是music21库里导进来的，你安装了music21库吗？

**Comment by bunnerlemon** [comment]
> ```
>             elif isinstance(element, chord.Chord):
>                 # print("chord=", '.'.join(str(data) for data in element.normalOrder))
>                 last_chord_idx = chord2int['.'.join(str(data) for data in element.normalOrder)]
>                 flag = False
> ```
> 
> 位置：data_pure.py 103行处
> 问题 ：chord处标红，显示：Unresolved reference 'chord'
> 我尝试着安装了chord，但是并没有作用
> 
> 谢谢您

我使用的chord是music21库里导进来的，你安装了music21库吗？

**Comment by Sususuqii** [comment]
您好，非常感谢您及时回答我。
我已经安装了music21 6.5.0

**Comment by Sususuqii** [comment]
D:\ANA\envs\py37\python.exe D:/graduate_code/LSTM/AutoMusic-master/data_pure.py
Traceback (most recent call last):
  File "D:/graduate_code/LSTM/AutoMusic-master/data_pure.py", line 217, in <module>
    data_pure()
  File "D:/graduate_code/LSTM/AutoMusic-master/data_pure.py", line 46, in data_pure
    num_count = convert(midi_stream)
  File "D:/graduate_code/LSTM/AutoMusic-master/data_pure.py", line 209, in convert
    if isinstance(element, note.Note) or isinstance(element, chord.Chord):
AttributeError: 'function' object has no attribute 'Chord'

**Comment by Sususuqii** [comment]
您好，我已经安装了music21 6.5.0

但是 chord标红的问题依旧没有解决

            elif isinstance(element, chord.Chord):
                # print("chord=", '.'.join(str(data) for data in element.normalOrder))
                last_chord_idx = chord2int['.'.join(str(data) for data in element.normalOrder)]
                flag = False
位置：data_pure.py 99 行处
问题 ：chord处标红，显示：Unresolved reference 'chord'

谢谢

**Comment by bunnerlemon** [comment]
> D:\ANA\envs\py37\python.exe D:/graduate_code/LSTM/AutoMusic-master/data_pure.py
> Traceback (most recent call last):
> File "D:/graduate_code/LSTM/AutoMusic-master/data_pure.py", line 217, in
> data_pure()
> File "D:/graduate_code/LSTM/AutoMusic-master/data_pure.py", line 46, in data_pure
> num_count = convert(midi_stream)
> File "D:/graduate_code/LSTM/AutoMusic-master/data_pure.py", line 209, in convert
> if isinstance(element, note.Note) or isinstance(element, chord.Chord):
> AttributeError: 'function' object has no attribute 'Chord'


错误提示为function object has no attribute 'Chord'，你是不是写了一个名为chord的函数?

**Comment by bunnerlemon** [comment]
> 您好，我已经安装了music21 6.5.0
> 
> 但是 chord标红的问题依旧没有解决
> 
> ```
>         elif isinstance(element, chord.Chord):
>             # print("chord=", '.'.join(str(data) for data in element.normalOrder))
>             last_chord_idx = chord2int['.'.join(str(data) for data in element.normalOrder)]
>             flag = False
> ```
> 
> 位置：data_pure.py 99 行处
> 问题 ：chord处标红，显示：Unresolved reference 'chord'
> 
> 谢谢

十分抱歉我的环境已经删掉了，目前没办法进行调试

**Comment by bunnerlemon** [comment]
> 您好，我已经安装了music21 6.5.0
> 
> 但是 chord标红的问题依旧没有解决
> 
> ```
>         elif isinstance(element, chord.Chord):
>             # print("chord=", '.'.join(str(data) for data in element.normalOrder))
>             last_chord_idx = chord2int['.'.join(str(data) for data in element.normalOrder)]
>             flag = False
> ```
> 
> 位置：data_pure.py 99 行处
> 问题 ：chord处标红，显示：Unresolved reference 'chord'
> 
> 谢谢

你可以试着写一个测试文件，看看你的music21是否可以正常使用

**Comment by Sususuqii** [comment]
好的，谢谢您，之前那个错误是我误写了一个函数，，标红问题我再看看，谢谢您啦

**Comment by Bin-love-ling** [comment]
你解决了这个问题吗

**Comment by parallaxlogicdevelopment** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @lxsamazing, @PythonFX, @qiaixing, @thurendous, @javapackage, @glrh111, @urnotlxr, @qlzw, @mymickey, @mheidari98, @MarkTangCd, @yangyuan6, @Cryptoyy, @aichizhajiang, @peng-huang-ch, @Loyalsoldier, @Wangzg97, @push-and-pop, @fireagainsmile, @tuoz, @mapping77, @3W1H, @JediChou, @haoyh, @yishengzijin, @newbee-12, @liyuan5087, @uvmv, @ouxch, @ck76, @zhaoqing2, @goxcc, @littledouzi, @0lh, @1429222731, @lilyang1989, @yujianFresh, @Linuzs, @compasty, @BurtChan, @kuro-tsuchi, @andyrus123, @yangyuhui, @lhmmhs, @panbin, @shishangx, @mekery, @dragon707, @jjeejj, @PigCharid

**Comment by parallaxlogicdevelopment** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @
